### PR TITLE
Make myft link go to myft root

### PR DESCRIPTION
**Pull request by laurieboyes**
So that the myft-page app can handle routing and users with saved articles aren't redirected to the product tour.

### CODE REVIEW

**Comment by keirog** [comment]
Might be better to only hit the minority with the extra redirect, so just redirect to saved-articles/tour from the following controller?

**Comment by laurieboyes** [comment]
Closing in favour of Keith's suggestion

**Comment by aintgoin2goa** [comment]
Just so you know, you don't need to release this component anymore - there's a navigation api as of next week and changes should be propagated to all apps running n-express 17

**Comment by laurieboyes** [comment]
The approach we tried had nasty side effects and its performance benefits were invalid - this is the better solution after all

**Pull request merged**
