### PR TITLE
Fix: decorateSelectedLink function

### PR DESCRIPTION
**Pull request by andygout**
cc @matthew-andrews @TheoLeanse 

Very hacky (regex!) and have got feeling may get fixed when vanity URLs are fully implemented, but thought I should flag.

Current function to mark a nav item as 'selected' based on the current path is:
`clonedItem.href === currentPath`

However, with the vanities, the `clonedItem`'s `href` value no longer matches the `currentPath` value (unless that will at some point be changed to the vanity format).

**currentPath**
`/stream/regionsId/TnN0ZWluX0dMX0pQ-R0w=`

**clonedItem**
```
     { name: 'Japan',
       id: 'TnN0ZWluX0dMX0pQ-R0w=',
       href: '/world/asia-pacific/japan' }
```

The only two values to check for a match is the `clonedItem`'s `id` and the last segment of `currentPath` (hence the regex).

### CODE REVIEW

**Comment by matthew-andrews** [comment]
Vanity URLs are completely implemented in this module now (I think there aren't any `/stream/tax/id` hrefs that aren't vanitied left now…)

I think a check along the lines of `"/stream/sectionsId/TMEID".indexOf('TMEID') !== -1` (ie. does the URL contain the ID) might be simpler and achieve more of less the same thing.

**Comment by matthew-andrews** [comment]
[also, sorry for breaking this 🙈]

**Comment by andygout** [comment]
Yup - makes sense.

**Comment by matthew-andrews** [comment]
+1

**Pull request merged**
