### PR TITLE
Ensure we pass through any non-vanity paths when setting up links

### PR DESCRIPTION
**Pull request by i-like-robots**
`req.get('ft-vanity-url') || req.path`

### CODE REVIEW

**Comment by matthew-andrews** [comment]
i _thought_ there was some middleware for this

**Comment by matthew-andrews** [comment]
nope, you're spot on.  hm, maybe we should improve this.  +1 for now.

**Comment by i-like-robots** [comment]
We don't get the expected result when presented with a barrier page. `req.path` in that case is prepended by `/barrier` so after logging in a user is again presented a barrier... what we need is the original request path which I'm not sure is available.

**Comment by matthew-andrews** [comment]
😭  such a mess. https://github.com/Financial-Times/n-express/blob/98b434db1e4328e601608a301033d9fb9abbf803/src/anon/middleware.js#L17-L19

**Comment by i-like-robots** [comment]
Bah https://github.com/Financial-Times/n-navigation/pull/136

**Pull request merged**
