### PR TITLE
Update nav.js

### PR DESCRIPTION
**Pull request by musthemag**
Moved Work & Career to the top level and added Alphaville to the Markets section. I hate Github, keeps failing on me!

### CODE REVIEW

**Comment by guyvalerio** [comment]
> added Alphaville to the Markets section
That wasn't agreed

**Comment by matthew-andrews** [comment]
🚓 😉  @musthemag

**Comment by guyvalerio** [comment]
Also...children of Bus Ed...thought we were going to delete them?

**Comment by i-like-robots** [comment]
What's the status of this @musthemag and @guyvalerio ?

**Comment by guyvalerio** [comment]
I _think_ this is supposed to be quick changes and that the bigger changes would be in another branch. @musthemag had a plan like that, I think.

**Comment by musthemag** [comment]
Correct Don Valerio

**Comment by i-like-robots** [comment]
Superseded by #117

**Pull request closed without merging**
